export const Images = [
  {
    id: 'BABY_PENGUIN',
    src: '/assets/images/baby_penguin.png',
    name: '걸어가는 펭귄 친구',
    positionX: 300,
    positionY: 55,
    maxWidth: 130,
    maxHeight: 80,
  },
  {
    id: 'BOXING_HAMSTER',
    src: '/assets/images/punch_hamster.png',
    name: '주먹왕 햄스터',
    positionX: 290,
    positionY: 260,
    maxWidth: 130,
    maxHeight: 300,
  },
  {
    id: 'THINKING_PUPPY',
    src: '/assets/images/thinking_puppy.png',
    name: '생각하는 강아지',
    positionX: 120,
    positionY: 110,
    maxWidth: 170,
    maxHeight: 145,
  },
  {
    id: 'EXCITED_DOG',
    src: '/assets/images/smile_puppy.png',
    name: '한껏 신난 강아지',
    positionX: 100,
    positionY: 80,
    maxWidth: 130,
    maxHeight: 110,
  },
  {
    id: 'PEEKING_PUPPY',
    src: '/assets/images/zoom_puppy.png',
    name: '빼꼼 쳐다보는 강아지',
    positionX: 110,
    positionY: 65,
    maxWidth: 130,
    maxHeight: 95,
  },
  {
    id: 'DRUNK_CAT',
    src: '/assets/images/wine_cat.png',
    name: '거나하게 취한 고양이',
    positionX: 300,
    positionY: 55,
    maxWidth: 130,
    maxHeight: 80,
  },
  {
    id: 'GRUMPY_CAT',
    src: '/assets/images/angry_cat.png',
    name: '심술난 고양이',
    positionX: 300,
    positionY: 330,
    maxWidth: 130,
    maxHeight: 350,
  },
];
